# Generated by Django 4.0 on 2022-02-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktails',
            name='garnish',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='taste',
            field=models.TextField(blank=True),
        ),
    ]
