# Generated by Django 4.0 on 2022-06-09 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ManyToManyField(blank=True, to='cocktails.BillingAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 18, 56, 28, 678593)),
        ),
    ]
