# Generated by Django 4.0 on 2022-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_alter_cocktails_garnish_alter_cocktails_pubdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='discount_price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='category',
            field=models.CharField(choices=[('M', 'Mocktails'), ('C', 'Cocktails')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='cocktails',
            name='price',
            field=models.FloatField(default=10.0),
        ),
    ]
