# Generated by Django 4.0 on 2022-06-09 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_payment_address_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 19, 5, 4, 523460)),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='address',
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
