# Generated by Django 4.0 on 2022-06-09 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_alter_order_ordered_date_remove_payment_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 19, 30, 44, 132262)),
        ),
    ]
