# Generated by Django 4.0 on 2022-02-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktails',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
