# Generated by Django 4.0 on 2022-07-02 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_alter_order_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='ordered',
            new_name='paiditems',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 24, 25, 635077)),
        ),
    ]
