# Generated by Django 4.0 on 2022-07-02 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_rename_ordered_payment_paiditems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paiditems',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 30, 34, 655690)),
        ),
    ]
