# Generated by Django 4.0 on 2022-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_billingaddress_phone_payment_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
