# Generated by Django 4.0 on 2022-04-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_payment_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='url',
        ),
    ]
