# Generated by Django 4.0 on 2022-07-02 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_alter_order_charge_alter_order_ordered_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='charge',
            new_name='mollie_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 39, 29, 680849)),
        ),
    ]
