# Generated by Django 4.0 on 2022-04-01 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_rename_link_payment__links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='_links',
            new_name='link',
        ),
    ]
