# Generated by Django 4.0 on 2022-04-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0012_rename__links_payment_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='charge',
        ),
    ]
