# Generated by Django 4.0 on 2022-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0016_alter_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
