# Generated by Django 4.0 on 2022-04-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0017_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
