# Generated by Django 4.0 on 2022-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0019_remove_order_items_order_items_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cocktails.OrderItem'),
        ),
    ]
