# Generated by Django 4.0 on 2022-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0025_payment_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
