# Generated by Django 4.0 on 2022-04-22 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0027_remove_order_ordered_date_alter_order_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 11, 48, 29, 873825)),
        ),
    ]
