# Generated by Django 4.0 on 2022-04-22 10:05

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0028_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 12, 5, 59, 363323)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
