# Generated by Django 4.0 on 2022-04-22 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0031_remove_order_items_order_ordereditems_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordereditems',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 19, 22, 30, 455118)),
        ),
    ]
