# Generated by Django 4.0 on 2022-06-09 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0033_remove_orderitem_order_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.ManyToManyField(blank=True, to='cocktails.BillingAddress'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='NotPaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 16, 8, 26, 980090)),
        ),
    ]
