# Generated by Django 4.0 on 2022-06-02 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0033_remove_orderitem_order_remove_order_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='adult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 28, 43, 531125)),
        ),
    ]
