# Generated by Django 4.0 on 2022-06-09 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0034_billingaddress_adult_billingaddress_consent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='NotPaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 14, 51, 11, 287768)),
        ),
    ]
