# Generated by Django 4.0 on 2022-06-09 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0034_billingaddress_adult_billingaddress_consent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 16, 8, 46, 159081)),
        ),
    ]
