# Generated by Django 4.0 on 2022-06-09 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0035_alter_order_ordered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='address',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 17, 58, 36, 959998)),
        ),
    ]
