# Generated by Django 4.0 on 2022-02-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(default='Dit is fake bodytext, vervang mij in de admin')),
                ('quotes', models.TextField(default='Dit is fake quotetext, vervang mij in de admin')),
            ],
        ),
    ]
