# Generated by Django 4.0 on 2022-02-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
